server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
    metadata-map:
      zone: zone1
    instance-id: ${spring.application.name}:${server.port}
  client:
    region: region-1
    service-url:
      zone1: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/