server:
  port: 8762

eureka:
  instance:
    hostname: eureka-peer2
  client:
    region: region-1
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka/,http://eureka-peer2:8762/eureka/