server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    metadata-map:
      zone: zone1
  client:
    region: region-1
    service-url:
      zone1: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/