#PROFILE
spring:
  profiles:
    active: zone1

eureka:
  healthcheck:
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    registry-fetch-interval-seconds: 5
    metadata-map:
      cluster: main
      zone: zone1
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/