#PROFILE
spring:
  profiles:
    active: zone1

eureka:
  healthcheck:
    enabled: true
  client:
    healthcheck:
      enabled: true
    prefer-same-zone-eureka: true
    region: region-1
    service-url:
      zone1: http://localhost:8761/eureka/,http://127.0.0.1:8762/eureka/
      zone2: http://127.0.0.1:8762/eureka/,http://localhost:8761/eureka/
    availability-zones:
      region-1: zone1,zone2