#PROFILE
spring:
  profiles:
    active: instance1

eureka:
  instance:
    metadata-map:
      zone: zone1
    instance-id: ${spring.application.name}:${server.port}
  healthcheck:
    enabled: true
  client:
    healthcheck:
      enabled: true
    prefer-same-zone-eureka: true
    region: region-1
    service-url:
      zone1: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
    availability-zones:
      region-1: zone1